In [23]:
import numpy as np
array = np.arange(25).reshape(5,5)
print("The array is: \n",  array)
print("The third row is: \n", array[2,:])
print("The fourth column is: \n", array[:,3])

The array is: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
The third row is: 
 [10 11 12 13 14]
The fourth column is: 
 [ 3  8 13 18 23]
