In [11]:
import numpy as np
array1 = np.array([7 ,21, 7, 5, 20, 24, 22, 25, 19, 2])
array2 = np.reshape(array1, (2,5))
print("Non-reshaped array is: \n", array1)
print("Reshaped 2x5 array is: \n", array2)
    

Non-reshaped array is: 
 [ 7 21  7  5 20 24 22 25 19  2]
Reshaped 2x5 array is: 
 [[ 7 21  7  5 20]
 [24 22 25 19  2]]
