In [7]:
import numpy as np
array1 = np.array([[2,3,4],[8,3,1]])
array2 = np.array([[2,9,9],[4,8,3],[3,6,6]])
array3 = np.concatenate((array1,array2))
print("The first array is: \n", array1)
print("The second array is: \n", array2)
print("The concatenated array is: \n", array3)

The first array is: 
 [[2 3 4]
 [8 3 1]]
The second array is: 
 [[2 9 9]
 [4 8 3]
 [3 6 6]]
The concatenated array is: 
 [[2 3 4]
 [8 3 1]
 [2 9 9]
 [4 8 3]
 [3 6 6]]
