In [9]:
import numpy as np
import random as rd
num1 = rd.randint(1,10)
num2 = rd.randint(1,10)
num3 = rd.randint(1,10)
num4 = rd.randint(1,10)
num5 = rd.randint(1,10)
num6 = rd.randint(1,10)
num7 = rd.randint(1,10)
num8 = rd.randint(1,10)
num9 = rd.randint(1,10)
print("The 3x3 matrix is: \n", np.matrix([[num1, num2, num3],[num4, num5, num6], [num7, num8, num9]]))

The 3x3 matrix is: 
 [[5 8 1]
 [4 8 3]
 [3 6 6]]
